# Generated by Django 4.2.13 on 2024-05-16 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales_entry", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesentrydata",
            name="added_date",
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
