# Generated by Django 4.2.13 on 2024-05-16 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales_entry", "0002_alter_salesentrydata_added_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesentrydata",
            name="payment_type",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
