# Generated by Django 4.2.13 on 2024-05-16 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales_entry", "0003_salesentrydata_payment_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesentrydata",
            name="auto_added_time",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
